#*****************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# project.tcl: Tcl script for re-creating project 'MikumariSecond-Ex'
#
# Generated by Vivado on Mon Oct 06 18:57:53 JST 2025
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/SiTCP_Netlist_for_Artix7/SiTCP_XC7A_32K_BBT_V110.edf"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1.xci"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/ip/div_tap/div_tap.xci"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/ip/mmcm_cdcm_second/mmcm_cdcm_second.xci"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/ip/divider/divider.xci"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/ip/clk_wiz_0/clk_wiz_0.xci"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CalPlateauThreshold_US.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/CalcCalibDelay.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/CalcFineLantency_US.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/Cdcm8RxImpl.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/Cdcm8TxImpl_verilog.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/SiTCP_Netlist_for_Artix7/SiTCP_XC7A_32K_BBT_V110.V"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/SiTCP_Netlist_for_Artix7/TIMER.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/SiTCP_Netlist_for_Artix7/WRAP_SiTCP_GMII_XC7A_32K.V"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_clocking.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_example_design.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_gt_common.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_reset_sync_ex.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_resets.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_support.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_sync_block_ex.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_tx_elastic_buffer.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/sitcp/mii_initializer.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/sitcp/network.v"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/bus_controller/defBusController.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/sitcp/defSiTCP.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/sitcp/defRBCP.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/bus_controller/BusController.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/defCDCM.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/ClockMonitor.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CdcmTxEncoder.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CdcmTxImpl.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/Cdcm8TxImpl.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/Cdcm8TxImpl_7s.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CdcmTx.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CbtTx.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CdcmRxDecoder.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CdcmRxImpl.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CdcmRx.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/Cdcm8RxImpl_7s.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CdcmRx_7s.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CbtRx.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/cbt/CbtLane.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/DelayGen.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/defLaccp.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/defHeartBeatUnit.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/utility/MyDPRamSRRT.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/utility/MyDPRamDE.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/utility/MyFifoComClock.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/HeartBeatUnit.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defLACCP_parameter.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/mikumari-link/defMikumari.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/LACCP_parameter.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/defBitwiseOp.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/LaccpBusSwitch.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/LaccpFrameRx.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/LaccpFrameTx.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/RLIGP.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/RCAP.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/LaccpMainBlock.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/mikumari-link/PRBS16.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/mikumari-link/MikumariTx.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/mikumari-link/MikumariRx.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/mikumari-link/MikumariLane.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/mikumari/mikumari-link/Wrapper/MikumariBlock.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/RstDelayTimer.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/SignalGen.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/bus_controller/defBusAddressMap.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/toplevel_SECOND.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/toplevel_SECOND_400MHz.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/synchronizer.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defCDCE62002Controller.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defFlashMemoryProgrammer.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defSPI_IF.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/sitcp/defMiiRstTimer.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defSelfDiagnosisSystem.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defSemImpl.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defResetGen.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defToplevel.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defLEDModule.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defMznInterface.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/main/defDCR.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/hdl/laccp/laccp/PrimaryHeartBeatUnit.vhd"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/ip/mmcm_cdcm_400MHz/mmcm_cdcm_400MHz.xci"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/constrs/pins.xdc"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/constrs/timing.xdc"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/constrs/impl.xdc"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/constrs/debug.xdc"
#    "/home/hamada/K_PRO/firmware/tmp/Secondary_K7/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_example_design.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/SiTCP_Netlist_for_Artix7/SiTCP_XC7A_32K_BBT_V110.edf"]"\
 "[file normalize "$origin_dir/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1.xci"]"\
 "[file normalize "$origin_dir/ip/div_tap/div_tap.xci"]"\
 "[file normalize "$origin_dir/ip/mmcm_cdcm_second/mmcm_cdcm_second.xci"]"\
 "[file normalize "$origin_dir/ip/divider/divider.xci"]"\
 "[file normalize "$origin_dir/ip/clk_wiz_0/clk_wiz_0.xci"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CalPlateauThreshold_US.v"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/CalcCalibDelay.v"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/CalcFineLantency_US.v"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/Cdcm8RxImpl.v"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/Cdcm8TxImpl_verilog.v"]"\
 "[file normalize "$origin_dir/SiTCP_Netlist_for_Artix7/SiTCP_XC7A_32K_BBT_V110.V"]"\
 "[file normalize "$origin_dir/SiTCP_Netlist_for_Artix7/TIMER.v"]"\
 "[file normalize "$origin_dir/SiTCP_Netlist_for_Artix7/WRAP_SiTCP_GMII_XC7A_32K.V"]"\
 "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_clocking.v"]"\
 "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_example_design.v"]"\
 "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_gt_common.v"]"\
 "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_reset_sync_ex.v"]"\
 "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_resets.v"]"\
 "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_support.v"]"\
 "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_sync_block_ex.v"]"\
 "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_tx_elastic_buffer.v"]"\
 "[file normalize "$origin_dir/hdl/sitcp/mii_initializer.v"]"\
 "[file normalize "$origin_dir/hdl/sitcp/network.v"]"\
 "[file normalize "$origin_dir/hdl/bus_controller/defBusController.vhd"]"\
 "[file normalize "$origin_dir/hdl/sitcp/defSiTCP.vhd"]"\
 "[file normalize "$origin_dir/hdl/sitcp/defRBCP.vhd"]"\
 "[file normalize "$origin_dir/hdl/bus_controller/BusController.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/defCDCM.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/ClockMonitor.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmTxEncoder.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmTxImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/Cdcm8TxImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/Cdcm8TxImpl_7s.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmTx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CbtTx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmRxDecoder.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmRxImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmRx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/Cdcm8RxImpl_7s.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmRx_7s.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CbtRx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CbtLane.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/DelayGen.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/defLaccp.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/defHeartBeatUnit.vhd"]"\
 "[file normalize "$origin_dir/hdl/utility/MyDPRamSRRT.vhd"]"\
 "[file normalize "$origin_dir/hdl/utility/MyDPRamDE.vhd"]"\
 "[file normalize "$origin_dir/hdl/utility/MyFifoComClock.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/HeartBeatUnit.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defLACCP_parameter.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/defMikumari.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/LACCP_parameter.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/defBitwiseOp.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/LaccpBusSwitch.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/LaccpFrameRx.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/LaccpFrameTx.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/RLIGP.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/RCAP.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/LaccpMainBlock.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/PRBS16.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/MikumariTx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/MikumariRx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/MikumariLane.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/Wrapper/MikumariBlock.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/RstDelayTimer.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/SignalGen.vhd"]"\
 "[file normalize "$origin_dir/hdl/bus_controller/defBusAddressMap.vhd"]"\
 "[file normalize "$origin_dir/hdl/toplevel_SECOND.vhd"]"\
 "[file normalize "$origin_dir/hdl/toplevel_SECOND_400MHz.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/synchronizer.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defCDCE62002Controller.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defFlashMemoryProgrammer.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defSPI_IF.vhd"]"\
 "[file normalize "$origin_dir/hdl/sitcp/defMiiRstTimer.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defSelfDiagnosisSystem.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defSemImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defResetGen.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defToplevel.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defLEDModule.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defMznInterface.vhd"]"\
 "[file normalize "$origin_dir/hdl/main/defDCR.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/PrimaryHeartBeatUnit.vhd"]"\
 "[file normalize "$origin_dir/ip/mmcm_cdcm_400MHz/mmcm_cdcm_400MHz.xci"]"\
 "[file normalize "$origin_dir/constrs/pins.xdc"]"\
 "[file normalize "$origin_dir/constrs/timing.xdc"]"\
 "[file normalize "$origin_dir/constrs/impl.xdc"]"\
 "[file normalize "$origin_dir/constrs/debug.xdc"]"\
 "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_example_design.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  set paths [list \
 "[file normalize "$origin_dir/[file normalize "$origin_dir/ip"]"]"\
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "MikumariSecond-Ex"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/build"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./build -part xc7k70tfbg484-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "customized_default_ip_location" -value "$origin_dir/ip" -objects $obj
set_property -name "default_lib" -value "mylib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7k70tfbg484-1" -objects $obj
set_property -name "platform.board_id" -value "kcu116" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "61" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "61" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "61" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "61" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "61" -objects $obj
set_property -name "webtalk.xcelium_export_sim" -value "1" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "61" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "29" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/ip"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/SiTCP_Netlist_for_Artix7/SiTCP_XC7A_32K_BBT_V110.edf"] \
 [file normalize "${origin_dir}/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1.xci"] \
 [file normalize "${origin_dir}/ip/div_tap/div_tap.xci"] \
 [file normalize "${origin_dir}/ip/mmcm_cdcm_second/mmcm_cdcm_second.xci"] \
 [file normalize "${origin_dir}/ip/divider/divider.xci"] \
 [file normalize "${origin_dir}/ip/clk_wiz_0/clk_wiz_0.xci"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CalPlateauThreshold_US.v"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/CalcCalibDelay.v"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/CalcFineLantency_US.v"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/Cdcm8RxImpl.v"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/Cdcm8TxImpl_verilog.v"] \
 [file normalize "${origin_dir}/SiTCP_Netlist_for_Artix7/SiTCP_XC7A_32K_BBT_V110.V"] \
 [file normalize "${origin_dir}/SiTCP_Netlist_for_Artix7/TIMER.v"] \
 [file normalize "${origin_dir}/SiTCP_Netlist_for_Artix7/WRAP_SiTCP_GMII_XC7A_32K.V"] \
 [file normalize "${origin_dir}/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_clocking.v"] \
 [file normalize "${origin_dir}/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_example_design.v"] \
 [file normalize "${origin_dir}/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_gt_common.v"] \
 [file normalize "${origin_dir}/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_reset_sync_ex.v"] \
 [file normalize "${origin_dir}/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_resets.v"] \
 [file normalize "${origin_dir}/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_support.v"] \
 [file normalize "${origin_dir}/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_sync_block_ex.v"] \
 [file normalize "${origin_dir}/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_tx_elastic_buffer.v"] \
 [file normalize "${origin_dir}/hdl/sitcp/mii_initializer.v"] \
 [file normalize "${origin_dir}/hdl/sitcp/network.v"] \
 [file normalize "${origin_dir}/hdl/bus_controller/defBusController.vhd"] \
 [file normalize "${origin_dir}/hdl/sitcp/defSiTCP.vhd"] \
 [file normalize "${origin_dir}/hdl/sitcp/defRBCP.vhd"] \
 [file normalize "${origin_dir}/hdl/bus_controller/BusController.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/defCDCM.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/ClockMonitor.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmTxEncoder.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmTxImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/Cdcm8TxImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/Cdcm8TxImpl_7s.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmTx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CbtTx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmRxDecoder.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmRxImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmRx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/Cdcm8RxImpl_7s.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmRx_7s.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CbtRx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CbtLane.vhd"] \
 [file normalize "${origin_dir}/hdl/main/DelayGen.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/defLaccp.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/defHeartBeatUnit.vhd"] \
 [file normalize "${origin_dir}/hdl/utility/MyDPRamSRRT.vhd"] \
 [file normalize "${origin_dir}/hdl/utility/MyDPRamDE.vhd"] \
 [file normalize "${origin_dir}/hdl/utility/MyFifoComClock.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/HeartBeatUnit.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defLACCP_parameter.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/defMikumari.vhd"] \
 [file normalize "${origin_dir}/hdl/main/LACCP_parameter.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/defBitwiseOp.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/LaccpBusSwitch.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/LaccpFrameRx.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/LaccpFrameTx.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/RLIGP.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/RCAP.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/LaccpMainBlock.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/PRBS16.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/MikumariTx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/MikumariRx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/MikumariLane.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/Wrapper/MikumariBlock.vhd"] \
 [file normalize "${origin_dir}/hdl/main/RstDelayTimer.vhd"] \
 [file normalize "${origin_dir}/hdl/main/SignalGen.vhd"] \
 [file normalize "${origin_dir}/hdl/bus_controller/defBusAddressMap.vhd"] \
 [file normalize "${origin_dir}/hdl/toplevel_SECOND.vhd"] \
 [file normalize "${origin_dir}/hdl/toplevel_SECOND_400MHz.vhd"] \
 [file normalize "${origin_dir}/hdl/main/synchronizer.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defCDCE62002Controller.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defFlashMemoryProgrammer.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defSPI_IF.vhd"] \
 [file normalize "${origin_dir}/hdl/sitcp/defMiiRstTimer.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defSelfDiagnosisSystem.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defSemImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defResetGen.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defToplevel.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defLEDModule.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defMznInterface.vhd"] \
 [file normalize "${origin_dir}/hdl/main/defDCR.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/PrimaryHeartBeatUnit.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/SiTCP_Netlist_for_Artix7/SiTCP_XC7A_32K_BBT_V110.edf"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "EDIF" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/ip/gig_ethernet_pcs_pma_1/gig_ethernet_pcs_pma_1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/div_tap/div_tap.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/mmcm_cdcm_second/mmcm_cdcm_second.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/divider/divider.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/clk_wiz_0/clk_wiz_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/hdl/mikumari/cbt/CalPlateauThreshold_US.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/CalcCalibDelay.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/CalcFineLantency_US.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/Cdcm8RxImpl.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/Cdcm8TxImpl_verilog.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/SiTCP_Netlist_for_Artix7/SiTCP_XC7A_32K_BBT_V110.V"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/SiTCP_Netlist_for_Artix7/TIMER.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/SiTCP_Netlist_for_Artix7/WRAP_SiTCP_GMII_XC7A_32K.V"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_clocking.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_example_design.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_gt_common.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_reset_sync_ex.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_resets.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_support.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_sync_block_ex.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_tx_elastic_buffer.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/sitcp/mii_initializer.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/sitcp/network.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/bus_controller/defBusController.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/sitcp/defSiTCP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/sitcp/defRBCP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/bus_controller/BusController.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/defCDCM.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/ClockMonitor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmTxEncoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmTxImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/Cdcm8TxImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/Cdcm8TxImpl_7s.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CbtTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmRxDecoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmRxImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/Cdcm8RxImpl_7s.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmRx_7s.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CbtRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CbtLane.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/DelayGen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/defLaccp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/defHeartBeatUnit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/utility/MyDPRamSRRT.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/utility/MyDPRamDE.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/utility/MyFifoComClock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/HeartBeatUnit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defLACCP_parameter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/defMikumari.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/LACCP_parameter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/defBitwiseOp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/LaccpBusSwitch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/LaccpFrameRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/LaccpFrameTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/RLIGP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/RCAP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/LaccpMainBlock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/PRBS16.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/MikumariTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/MikumariRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/MikumariLane.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/Wrapper/MikumariBlock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/RstDelayTimer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/SignalGen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/bus_controller/defBusAddressMap.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/toplevel_SECOND.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/toplevel_SECOND_400MHz.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/synchronizer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defCDCE62002Controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defFlashMemoryProgrammer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defSPI_IF.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/sitcp/defMiiRstTimer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defSelfDiagnosisSystem.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defSemImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defResetGen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defToplevel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defLEDModule.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defMznInterface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/main/defDCR.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/PrimaryHeartBeatUnit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "toplevel_SECOND" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/mmcm_cdcm_400MHz/mmcm_cdcm_400MHz.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/mmcm_cdcm_400MHz/mmcm_cdcm_400MHz.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/pins.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/pins.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/timing.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/timing.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/impl.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/impl.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/debug.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/debug.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_example_design.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/gig_ethernet_pcs_pma_1_ex/imports/gig_ethernet_pcs_pma_1_example_design.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/constrs/debug.xdc"]" -objects $obj
set_property -name "target_part" -value "xc7k70tfbg484-1" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/constrs/debug.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "toplevel_SECOND" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "mylib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7k70tfbg484-1 -flow {Vivado Synthesis 2023} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2023" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7k70tfbg484-1" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7k70tfbg484-1 -flow {Vivado Implementation 2023} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2023" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7k70tfbg484-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
