set_property PACKAGE_PIN E22 [get_ports {LED[1]}]
set_property PACKAGE_PIN E21 [get_ports {LED[2]}]
set_property PACKAGE_PIN F21 [get_ports {LED[3]}]
set_property PACKAGE_PIN G21 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {NIM_OUT[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {NIM_OUT[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {NIM_OUT[1]}]
set_property PACKAGE_PIN A10 [get_ports {NIM_OUT[3]}]
set_property PACKAGE_PIN A14 [get_ports {NIM_OUT[2]}]
set_property PACKAGE_PIN A13 [get_ports {NIM_OUT[1]}]
set_property PACKAGE_PIN D15 [get_ports MIKUMARI_RXP]
set_property PACKAGE_PIN A20 [get_ports MIKUMARI_TXP]

set_property PACKAGE_PIN E17 [get_ports OSC]
set_property IOSTANDARD LVCMOS25 [get_ports OSC]
set_property IOSTANDARD LVDS_25 [get_ports MIKUMARI_RXP]
set_property IOSTANDARD LVDS_25 [get_ports MIKUMARI_RXN]
set_property IOSTANDARD LVDS_25 [get_ports MIKUMARI_TXP]
set_property IOSTANDARD LVDS_25 [get_ports MIKUMARI_TXN]
set_property PACKAGE_PIN R19 [get_ports PROGB_ON]
set_property PACKAGE_PIN W15 [get_ports USR_RST]
set_property IOSTANDARD LVCMOS33 [get_ports PROGB_ON]
set_property IOSTANDARD LVCMOS33 [get_ports USR_RST]
set_property PULLDOWN true [get_ports USR_RST]

set_property PACKAGE_PIN D6 [get_ports sfp_refclk_p]
set_property PACKAGE_PIN D2 [get_ports sfp_tx_p]
set_property PACKAGE_PIN B18 [get_ports heartbeat_P]
set_property IOSTANDARD LVDS_25 [get_ports heartbeat_P]


